### ISSUE TITLE
Nightly failure: *rc <= storage_rc

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#2556] opened 2020-04-28 17:52 UTC
Run: http://nightly.neartest.com/run/2cef4105736ab969470df2751e78fd3f0fc0a81d_200428_102644

`transaction.py`, see `log3`:

```
thread 'main' panicked at 'assertion failed: *rc <= storage_rc', core/store/src/trie/mod.rs:503:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/liballoc/boxed.rs:1031
  11: near_primitives::test_utils::init_stop_on_panic::{{closure}}::{{closure}}
             at core/primitives/src/test_utils.rs:83
  12: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  13: std::panicking::begin_panic
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panicking.rs:438
  14: near_store::trie::TrieChanges::deletions_into_inner
             at core/store/src/trie/mod.rs:503
  15: near_store::trie::TrieChanges::deletions_into
             at core/store/src/trie/mod.rs:487
  16: near_chain::store::ChainStoreUpdate::clear_block_data::{{closure}}
             at chain/chain/src/store.rs:1771
  17: core::option::Option<T>::map
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/option.rs:456
  18: near_chain::store::ChainStoreUpdate::clear_block_data
             at chain/chain/src/store.rs:1768
  19: near_chain::chain::Chain::clear_data
             at chain/chain/src/chain.rs:574
  20: near_client::client::Client::on_block_accepted
             at chain/client/src/client.rs:751
  21: near_client::client_actor::ClientActor::process_accepted_blocks
             at chain/client/src/client_actor.rs:692
  22: near_client::client_actor::ClientActor::process_block
             at chain/client/src/client_actor.rs:733
  23: near_client::client_actor::ClientActor::receive_block
             at chain/client/src/client_actor.rs:755
  24: <near_client::client_actor::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
             at chain/client/src/client_actor.rs:281
  25: <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.9.0/src/address/envelope.rs:112
  26: <actix::address::envelope::Envelope<A> as actix::address::envelope::EnvelopeProxy>::handle
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.9.0/src/address/envelope.rs:71
  27: actix::mailbox::Mailbox<A>::poll
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.9.0/src/mailbox.rs:101
  28: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.9.0/src/contextimpl.rs:373
  29: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/future/future.rs:118
  30: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/core.rs:163
  31: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/loom/std/unsafe_cell.rs:14
  32: tokio::runtime::task::core::Core<T,S>::poll
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/core.rs:148
  33: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/harness.rs:108
  34: core::ops::function::FnOnce::call_once
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/ops/function.rs:232
  35: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panic.rs:318
  36: std::panicking::try::do_call
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panicking.rs:331
  37: __rust_try
  38: std::panicking::try
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panicking.rs:274
  39: std::panic::catch_unwind
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panic.rs:394
  40: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/harness.rs:84
  41: tokio::runtime::task::raw::poll
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/raw.rs:104
  42: tokio::runtime::task::raw::RawTask::poll
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/raw.rs:66
  43: tokio::runtime::task::Notified<S>::run
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/mod.rs:169
  44: tokio::task::local::LocalSet::tick::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/task/local.rs:406
  45: tokio::coop::budget::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/coop.rs:85
  46: std::thread::local::LocalKey<T>::try_with
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/thread/local.rs:262
  47: std::thread::local::LocalKey<T>::with
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/thread/local.rs:239
  48: tokio::coop::budget
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/coop.rs:79
  49: tokio::task::local::LocalSet::tick
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/task/local.rs:406
  50: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/task/local.rs:527
  51: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/macros/scoped_tls.rs:64
  52: tokio::task::local::LocalSet::with
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/task/local.rs:440
  53: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/task/local.rs:516
  54: std::future::poll_with_tls_context
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:99
  55: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/task/local.rs:390
  56: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:44
  57: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/basic_scheduler.rs:131
  58: tokio::coop::budget::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/coop.rs:97
  59: std::thread::local::LocalKey<T>::try_with
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/thread/local.rs:262
  60: std::thread::local::LocalKey<T>::with
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/thread/local.rs:239
  61: tokio::coop::budget
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/coop.rs:79
  62: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/basic_scheduler.rs:131
  63: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/basic_scheduler.rs:213
  64: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/macros/scoped_tls.rs:64
  65: tokio::runtime::basic_scheduler::enter
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/basic_scheduler.rs:213
  66: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/basic_scheduler.rs:123
  67: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/mod.rs:418
  68: tokio::runtime::context::enter
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/context.rs:72
  69: tokio::runtime::handle::Handle::enter
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/handle.rs:39
  70: tokio::runtime::Runtime::block_on
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/mod.rs:415
  71: tokio::task::local::LocalSet::block_on
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/task/local.rs:351
  72: actix_rt::runtime::Runtime::block_on
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.0/src/runtime.rs:89
  73: actix_rt::builder::SystemRunner::run
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.0/src/builder.rs:164
  74: neard::main
             at neard/src/main.rs:199
  75: std::rt::lang_start::{{closure}}
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/rt.rs:67
  76: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  77: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  78: std::panicking::try
             at src/libstd/panicking.rs:274
  79: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  80: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  81: std::rt::lang_start
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/rt.rs:67
  82: main
  83: __libc_start_main
  84: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bowenwang1996** [comment] 2020-04-28 18:09
likely the same issue as https://github.com/nearprotocol/nearcore/issues/2500

**Comment by SkidanovAlex** [comment] 2020-04-29 00:49
Failed again in the latest run:
http://nightly.neartest.com/run/78065f8fbb864c518179efe5150c65fc3d2b23e4_200429_001719

**Comment by damons** [comment] 2020-05-01 16:31
@Kouprin Indicated to me that this is exactly the same bug as #2500 as @bowenwang1996 suggests.  Should we close this as a duplicate?

**Comment by damons** [comment] 2020-05-01 16:44
I retract my previous comment.  It may not be exactly the same as #2500.

**Comment by bowenwang1996** [comment] 2020-05-01 23:41
It mostly like is caused by the same issue. However, let's wait until the underlying issue is fixed before closing it.

**Closed** 2020-05-18 04:42 UTC
Labels: chain, nightly
