### ISSUE TITLE
Suspicious balance changes during the token transfer

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1728] opened 2019-11-19 07:34 UTC
As reported by @SkidanovAlex 

> I start from a state in which two accounts all have 1000000000000000000000000000 tokens. I issue a transfer tx from one account to another to transfer 100 tokens, and end up in a state with first account having 999999999999999999999996534 and the second 1000000000000000000000000694.
> Those numbers do not add up to 2000000000000000000000000000, where did the remainder go? Why did the second account receive more than 100 that was sent to them?
> 
> the test is in pytest/tests/sanity/transactions.py if you want to run it, you'll need to install dependencies from pytest/requirements.txt and run it from pytest as the working dir

**Comment by nearmax** [comment] 2019-11-19 07:35
FYI @evgenykuzyakov

**Comment by nearmax** [comment] 2019-11-19 07:38
> Though it has a typo in the line that will fail, the assert that fires tries to trace expected_balances instead of ctx.expected_balances. The line should be

`assert cur_balances == ctx.expected_balances, "%s != %s" % (cur_balances, ctx.expected_balances)`

**Comment by bowenwang1996** [comment] 2019-11-19 16:09
Duplicate of #1704

**Closed by bowenwang1996** 2019-11-19 16:09 UTC
Labels: Priority 0, bug, runtime, runtime-stability
