### ISSUE TITLE
Connection reset by peer when peer is at capacity

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2521] opened 2020-04-24 11:43 UTC
**Describe the bug**
When trying to connect to a node that already have max_peers, the connection gets reset without providing alternative peers. For bootnodes this leads to new peers not able to connect to network at all.

**To Reproduce**
1. Spin up a node A with max_peers=1. 
2. Spin up a node B with normal max_peers and connect it to node A.
3. Spin up a node C, with boot node as A.
Observe C not connecting to anyone.

**Expected behavior**
Node C should connect to B.

**Additional context**
Blocking new nodes on betanet

**Comment by bowenwang1996** [comment] 2020-04-24 14:30
I don’t think the situation you described is a bug. It seems to me that this is expected behavior. The problem with actual network is supposedly fixed in https://github.com/nearprotocol/nearcore/pull/2490

**Comment by ilblackdragon** [comment] 2020-04-24 14:41
Why would this be an expected behavior? Boot nodes should respond with alternatives if they are too busy.

**Comment by mfornet** [comment] 2020-04-24 16:59
@ilblackdragon The solution to this problem was described in #2395 and solved in #2490. 

`max_peer` is a hard limit that should not be passed ever, but to address the issue when new peers try to connect we establish an ideal number of connections which should be strictly less than `max_peer`. If at any moment in time active connections is greater than ideal number of connections, some connections get dropped.

Check #2395 To see full proposal. I explored this idea on the [following script](https://gist.github.com/mfornet/583393d7e350617ce65765dacb91f15a) and results are encouraging. In a test with 1000 nodes this are the results:

```
Number of edges that were created and removed among all nodes: 16276
Removed edges: 177
Created edges: 16099
Mean edge updates per node: 16.1

Network diameter: 3

Stats of active peers
Minimum number of active peers a node have: 30
Mean active peers among all nodes: 31.84
Maximum number of active peers a node have: 35

Stats of Outbound:
Minimum number of outbound connection a node have: 8
Mean outbound connection among all nodes: 15.92
Maximum number of outbound connections a node have: 24
```

Stats indicate the network converge really fast (16 updates on average on a 1000 nodes network) to a healthy point. All nodes have required number of outbound connections and ideal connections are in the required limit, so new connections will be accepted.

The follow up of this test, is that after this point new nodes were able to connect without trouble and without affecting health of the network.

**Comment by mfornet** [comment] 2020-04-24 17:06
Also added a verification to the configs, since not every possible configuration will work. [Check it here](https://github.com/nearprotocol/nearcore/pull/2490/files#diff-b641e34503306b0eaee79d1eaeaccb68R763)

**Comment by bowenwang1996** [comment] 2020-04-25 17:51
> The follow up of this test, is that after this point new nodes were able to connect without trouble and without affecting health of the network.

Does this test exist?

**Comment by mfornet** [comment] 2020-04-26 08:04
> > The follow up of this test, is that after this point new nodes were able to connect without trouble and without affecting health of the network.
> 
> Does this test exist?

[It does exist.](https://github.com/nearprotocol/nearcore/blob/master/chain/network/tests/full_network.rs#L74)

**Comment by bowenwang1996** [comment] 2020-04-26 17:34
@mfornet what I meant is to test it on a larger scale. Say we have ~80 nodes in the network and they all boot from say 8 nodes, will the resulting network be healthy (no node reaching maximum capacity).

**Comment by ilblackdragon** [comment] 2020-04-26 21:48
Also @mfornet right now one can not change max_peers, because getting:
```
Inestable IDEAL_CONNECTIONS_HI(35) compared with MAX_PEERS(1)
```
It seems like `IDEAL_CONNECTIONS_HI` as a constant:
```
neard/src/config.rs:pub const IDEAL_CONNECTIONS_HI: u32 = 35;
neard/src/config.rs:                ideal_connections_hi: IDEAL_CONNECTIONS_HI,
```

**Comment by mfornet** [comment] 2020-04-28 05:21
@ilblackdragon IDEAL_CONNECTIONS is a constant, I can move it to config, for the sake of manually testing. This has the drawback of polluting the config file. Why are you setting `max_peer` to 1?

In general one node might not work good if the NetworkConfig is misconfigured, that is why it is enforced on runtime, but it can work. So one option is displaying errors without panic. This has the drawback that the node will be creating and dropping connections constantly on some situations, and some invariants can be broken about number of peers can be broken, but I expect it will not make the node crash.

**Comment by bowenwang1996** [comment] 2020-04-28 14:38
@mfornet there is no reason that `max_peer` is in config while the number of ideal connections are not. In fact, we may change the number 40 if we think it doesn't work well. If you do not want to put them in config you can derive them from `max_peer` using some pre-defined formula. Also please see my earlier comment on testing https://github.com/nearprotocol/nearcore/issues/2521#issuecomment-619591578

**Closed** 2020-04-30 21:37 UTC
Labels: bug
