### ISSUE TITLE
Feedback on opening store database

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#2768] opened 2020-06-02 19:29 UTC
**Describe the bug**

When the node is starting it is stuck for over 15 minutes at:

```
Jun 02 19:18:09.246  INFO near: Version: 0.4.13, Build: aac14605
Jun 02 19:18:09.404  INFO near: Opening store database at "/srv/near/data"
```

I already stopped the node and moved `~/.near/betanet/data` to other location to start over with clean database. I saved this data so I can test against it in the future.

**To Reproduce**
My node was previously running on betanet. I just stopped it and on restart hit the described scenario. It is worth noticing currently my `~/.near/betanet/data` folder is 54.1GB large.

I'm using `nearup betanet` to run the node.

**Expected behavior**
I expect to have some feedback or progress back while opening the store, or pass this step immediately.

**Comment by bowenwang1996** [comment] 2020-06-02 19:54
Duplicate of #2105

**Closed by bowenwang1996** 2020-06-02 19:54 UTC
