### ISSUE TITLE
Small bug in "near validators" output: last validator always has 0 seats 

### ISSUE THREAD

**Issue by Cloudpostru** [nearprotocol/nearcore#2783] opened 2020-06-03 22:23 UTC
OS: Ububntu 18.04
NEAR: version: 0.4.13, build:2d02b333

There is small bug in the following commands output:
```
near validators current
near validators next
```
Last validator always has 0 seats 
![Bug](https://user-images.githubusercontent.com/28756593/83695011-ebd4ee80-a601-11ea-8530-4adbe3f154cb.PNG)
(however he has 1 last seat).

**Comment by bowenwang1996** [comment] 2020-06-03 23:00
Duplicate of https://github.com/near/near-shell/issues/385

**Closed by bowenwang1996** 2020-06-03 23:00 UTC
