### ISSUE TITLE
RPC batching

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2008] opened 2020-01-23 02:07 UTC
Our clients want avoid the following race condition that can happen on RPC:

Suppose we want to query both the account info and the access keys of the account at the same time. Unfortunately, these are available through separate RPC requests. They can issue request for account state (suppose they get state at block X), but then when they query access keys get them at block X+Y. They try to re-query the state, but now it is at the block X+Y+Z, etc. This DevX does not seem nice, it would be better if they could issue a single RPC that batches several queries and returns there results all at the given block height.

**Comment by vgrichina** [comment] 2020-01-23 02:14
@nearmax will it also work for submitting transactions? It'll be cool to be able to submit them in batch to avoid `nonce` issues that can be caused by HTTP requests being re-ordered.

**Comment by nearmax** [comment] 2020-01-23 02:18
> @nearmax will it also work for submitting transactions? It'll be cool to be able to submit them in batch to avoid `nonce` issues that can be caused by HTTP requests being re-ordered.

@vgrichina In what case would you want to submit several transaction in on batch rather than batching actions within these transactions and submitting it as one transaction?

**Comment by nearmax** [comment] 2020-01-23 19:18
> @nearmax I prefer to only allow `query` batching (and implement it without a lock). What is your opinion?

So we will hide the retries inside our RPC handler?

**Comment by frol** [comment] 2020-01-23 20:01
Well, I have just read the `query` API and it turned out to have `call` and `contract` [aka `view_state`] methods, which actually execute some code, and even mutate data (in the case of `call`).

> Also, I don't think we need retries. If our first query returns account state at block X, then we should specify this block X when performing the next query. 

Should we just expose this ability to query account and access keys status by block hash then instead of complicating our API with batch interfaces?

**Comment by nearmax** [comment] 2020-01-23 20:13
I think our RPC queries should support specifying block hash. This sounds like a good idea which is generic enough.

**Comment by frol** [comment] 2020-01-23 20:26
Closing in favor of #2015.

**Closed by frol** 2020-01-23 20:26 UTC
Labels: Priority 0, rpc
