### ISSUE TITLE
Fix and include state_sync_massive.py in nightly

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#2733] opened 2020-05-27 16:22 UTC
Currently state_sync_massive.py is not working. Fix it and add it to nightly tests.

Read for more details: https://github.com/nearprotocol/nearcore/pull/2714#issuecomment-634393198

#2515 partially address the issues on this test.

**Comment by bowenwang1996** [comment] 2020-05-27 21:24
Duplicate of #2512. Let's keep discussions there.

**Closed by bowenwang1996** 2020-05-27 21:24 UTC
