### ISSUE TITLE
CI for external contributors

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#1067] opened 2019-07-12 02:37 UTC
It seems that our CI does not pick up the commits in PRs submitted by external contributors. This needs to be fixed.

**Comment by Zimmi48** [comment] 2019-07-17 08:42
GitLab CI for GitHub repositories indeed does not automatically pick up PRs from forks. The reason why it builds PRs from core contributors is because they push to branches which are mirrored on the GitLab repository.

I am the maintainer of @coqbot which is a bot that can synchronize PRs with GitLab branches, and that @ilblackdragon has activated on this repo (which is how I learned about it). The PR synchronization process is working correctly, as can be seen in https://gitlab.com/near-protocol/nearcore/pipelines. However, the status reporting part was not fully activated. This is likely to become a problem because what the bot does is to merge the PR branch with the base branch (exactly like Travis does) in order to run CI not on the branch itself (which may be outdated) but on what would be the result if this PR was merged. Unfortunately, this means that the GitLab feature for reporting status checks back won't work correctly (it will report status for merge commits -- which do not exist on GitHub -- instead of reporting them for the head commit of the PR). This is why the status reporting part of the bot is not really an optional bonus, and you should activate it by setting up the `/pipeline` webhook on GitLab CI (the `/job` webhook is a bonus if you want detail reports about the failures). If you do not like this automatic merging feature and would rather have the bot push the PR branch as-is and leave the status check reporting to GitLab, then I suggest you open a feature request at https://github.com/coq/bot/issues so that we can discuss it.

**Comment by ilblackdragon** [comment] 2019-07-17 15:17
@Zimmi48 I've set up `/pipeline` and `/job` webhooks on Gitlab when was setting up @coqbot 
<img width="676" alt="Screen Shot 2019-07-17 at 8 13 13 AM" src="https://user-images.githubusercontent.com/175486/61387330-ccf32f80-a86a-11e9-821f-8adf03397e0a.png">

Also I do see status report from @coqbot in Github:
<img width="720" alt="Screen Shot 2019-07-17 at 8 14 30 AM" src="https://user-images.githubusercontent.com/175486/61387409-ee541b80-a86a-11e9-9f6f-22de41fa8c4e.png">

(the "ci/gitlab/script-fixed" is the old one I disabled)

So from my perspective all works, @Zimmi48 do you see something missing right now?

**Comment by Zimmi48** [comment] 2019-07-17 16:59
The status checks you see on this PR are the ones from GItLab itself, not @coqbot. There is a problem as can be seen on the last commit on master which did not get any status check reported. But I understand what the issue is now: the GitLab repo and the GitHub repo do not have the same fullname (because of the dash in the organization name). @coqbot will push changes from GitHub to GitLab and these are redirected to the new URL. However, in the reverse direction, @coqbot will try to push the status checks to near-protocol/nearcore and this won't work.

Solution 1: rename GitLab organization to match GitHub organization.
Solution 2: rename GitHub organization to match GitLab organization
Solution 3: I need to change @coqbot, either by hard coding a special case for this project, or by making it possible to configure this correspondence (the latter would be the best long term solution, but also the one that would take the longest to implement).

**Comment by ilblackdragon** [comment] 2019-07-19 02:43
@Zimmi48 I would love to use Solution (1), but I get "namespace directory cannot be moved" when renaming near-protocol to nearprotocol. (https://gitlab.com/gitlab-org/gitlab-ce/issues/36197)
Solution (2) kind of sucks in our case, as it's a gitlab issues that we need to have name with dash.

If you going to look into configuration - that probably would be good for lots of projects.

**Comment by Zimmi48** [comment] 2019-07-19 07:58
I'll start by hard coding the correspondence for your case, and then look into making it configurable.

**Comment by Zimmi48** [comment] 2019-07-19 08:12
Done. Should work now hopefully. You can test by resending one of the GitLab webhook if you want (you need to click Edit then select one of the recently sent webhook, and there's an option to resend it).

**Comment by Zimmi48** [comment] 2019-07-21 18:07
FTR @coqbot is currently correctly pushing the status checks to the correct repository, but it does not work because it does not have write-access. I suppose it has been removed from the collaborators, sometime after having been added...

**Comment by ilblackdragon** [comment] 2019-07-22 02:02
@Zimmi48 Oh, it had `Read` permissions only, just switched it to `Write`.
Thanks a lot for the hot fix! I'll test it with a real PR in a bit :)

**Comment by ailisp** [comment] 2019-10-11 00:18
We now host a similar bot but more reliable @nearprotocol-ci

**Closed by ailisp** 2019-10-11 00:18 UTC
Labels: housekeeping

**Comment by Zimmi48** [comment] 2019-10-11 00:34
Would have loved to hear about the reliability issues you had.
