### ISSUE TITLE
Extraneous Telemetry INFO Logging 

### ISSUE THREAD

**Issue by damons** [nearprotocol/nearcore#2824] opened 2020-06-09 22:27 UTC
**Description**

Currently INFO log level reports when telemetry data cannot be sent:

 ```
Jun 09 17:04:30.024  INFO telemetry: Telemetry data could not be sent due to: Timeout out while waiting for response
Jun 09 17:04:40.026  INFO stats: # 6942514 49mtsn1AHuy734t6iS8QPzCBn6325qwA7BDZvsJG7div -/86  6/6/40 peers ⬇ 28.9kiB/s ⬆ 26.0kiB/s 0.80 bps 0 gas/s CPU: 8%, Mem: 988.2 MiB    
Jun 09 17:04:40.027  INFO telemetry: Telemetry data could not be sent due to: Timeout out while waiting for response
Jun 09 17:04:50.040  INFO stats: # 6942521 GJwfkf34iWdst47sJ99xRoYMemKCu9zJ4AvqdA8mC5Yn -/86  6/6/40 peers ⬇ 29.2kiB/s ⬆ 26.1kiB/s 0.70 bps 0 gas/s CPU: 7%, Mem: 988.2 MiB    
Jun 09 17:04:50.040  INFO telemetry: Telemetry data could not be sent due to: Timeout out while waiting for response
Jun 09 17:05:00.075  INFO stats: # 6942528 Fh5Y7F6WoPC2tNVZJwDz2mebdcdbwwJFF2pi61Y9nHbp -/86  6/6/40 peers ⬇ 30.0kiB/s ⬆ 26.2kiB/s 0.70 bps 0 gas/s CPU: 6%, Mem: 988.2 MiB    
Jun 09 17:05:00.076  INFO telemetry: Telemetry data could not be sent due to: Timeout out while waiting for response
Jun 09 17:05:10.078  INFO stats: # 6942534 85mdE5zgXrXSSzbM4YRfM1Vk3UnD7pu1SThGyEA9GAfp -/86  6/6/40 peers ⬇ 29.9kiB/s ⬆ 26.1kiB/s 0.60 bps 0 gas/s CPU: 7%, Mem: 988.2 MiB    
Jun 09 17:05:10.079  INFO telemetry: Telemetry data could not be sent due to: Timeout out while waiting for response
Jun 09 17:05:20.081  INFO stats: # 6942541 AGtzgtMccZCKz9oq5quDtZNZ6ennpsosdSTCFTijkfAg -/86  6/6/40 peers ⬇ 30.4kiB/s ⬆ 26.9kiB/s 0.70 bps 0 gas/s CPU: 7%, Mem: 988.2 MiB    
Jun 09 17:05:20.082  INFO telemetry: Telemetry data could not be sent due to: Timeout out while waiting for response
Jun 09 17:05:30.084  INFO stats: # 6942548 7ykBVdwiCV6YfRD7oZbdp6MwnfzWFACc4RX1B1SMfF4v -/86  6/6/40 peers ⬇ 31.2kiB/s ⬆ 27.4kiB/s 0.70 bps 0 gas/s CPU: 6%, Mem: 988.2 MiB    
Jun 09 17:05:30.085  INFO telemetry: Telemetry data could not be sent due to: Timeout out while waiting for response
```

Are there actions an admin can take to eliminate the timeout warnings?

If not, can we reduce the Telemetry log entries into something more meaningful for the user?  IMO, the logs could be used to report different categories of entries: 

1.  Indications that build trust that all systems are nominal.
2.  Actionable issues when problems exist.
3.  Reporting of non-critical problems that do not require any action but *can* be resolved by admin actions.
4.  Reporting of problems that do not affect normal operations of the node but cannot be resolved by any action by an admin.

For some reason, I'm inclined to not include type 4 items because all it does is introduce fear, uncertainty, and doubt for a working node when there's nothing anyone can do about it.  But, I also understand if people just want to see these warnings all the time.  For me, they seem to be extraneous.

**To Reproduce**

Run a beta branch node.   View the log.

**Expected behavior**

Log entries are only of types 1-3 described above.

**Version (please complete the following information):**
- nearcore ``commit 74bfab78f23debde7b8d778e42ee17fc4850dcab (HEAD -> beta, tag: beta-2020-06-07, origin/beta)``
- rust version :  1.44.0
- no docker
- beta

**Comment by bowenwang1996** [comment] 2020-06-10 02:25
duplicate of https://github.com/nearprotocol/nearcore/issues/2798

**Closed by bowenwang1996** 2020-06-10 02:25 UTC
