### ISSUE TITLE
Clear storage from old blocks and state diffs

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1023] opened 2019-06-23 18:20 UTC
Requires state sync.

After some number of epochs in the past, we can be sure that blocks, transactions and state diffs are not needed any more (some multiplier of the `block_fetch_horizon` from #1007).

Add a flag `--archive` if the node runner actually wants to keep the data.

**Comment by SkidanovAlex** [comment] 2020-02-10 13:49
Partial duplicate of #1648

**Comment by Kouprin** [comment] 2020-03-31 07:33
Resolved in https://github.com/nearprotocol/nearcore/pull/2084

**Closed by Kouprin** 2020-03-31 07:33 UTC
Labels: P1, chain
