### ISSUE TITLE
NearConfig in RPC

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2007] opened 2020-01-23 02:02 UTC
We need to make Near config query-able through node RPC. Specifically, one of our clients wants to have know how many blocks remain until an account is going to be evicted due to rent. This information can be derived from the account balance and the config.

**Comment by frol** [comment] 2020-01-23 16:54
The config includes quite an amount of information which is also nested and, what is even more important, sensitive (e.g. `secret_key`, `account_id` [?], `boot_nodes` [?], `blacklist` [?], etc; we need to review [the `near/src/config.rs:NearConfig`](https://github.com/nearprotocol/nearcore/blob/master/near/src/config.rs)). Given we want to expose the information in a backward-compatible way, we don't need to make the structs serializable, but instead, we come up with a config structure, which makes sense for the users.

@nearmax What are the fields the users are interested in their particular use-case?

**Comment by frol** [comment] 2020-01-23 19:01
Also, access to `NearConfig` from `chain/jsonrpc` is tricky, as it combines `near_client::ClientConfig`, `near_chain::ChainGenesis`, `near_network::NetworkConfig`, `near_runtime::RuntimeConfig`, and a number of other modules.

**Comment by nearmax** [comment] 2020-01-23 19:15
> @nearmax What are the fields the users are interested in their particular use-case?

I think RuntimeConfig (when we solve upgradability RuntimeConfig will depend on the block hash https://github.com/nearprotocol/nearcore/issues/1994), ClientConfig, GenesisConfig.

**Comment by frol** [comment] 2020-01-23 19:33
@nearmax I am considering adding *ConfigView structs to `chain/jsonrpc` (I have also considered `core/primitives`, but I don't want to pollute them even more) to resolve the issue of inappropriate inter-dependencies. Do you have better suggestions?

**Comment by nearmax** [comment] 2020-01-23 20:15
> @nearmax I am considering adding *ConfigView structs to `chain/jsonrpc` (I have also considered `core/primitives`, but I don't want to pollute them even more) to resolve the issue of inappropriate inter-dependencies. Do you have better suggestions?

@frol Why do we need additional structures? `RuntimeConfig`, `ClientConfig`, and `GenesisConfig` do not seem to be exposing any sensitive data so we can directly return them.

**Comment by frol** [comment] 2020-01-23 20:23
@nearmax For example, `RuntimeConfig` is defined in `runtime/runtime`, which is not a dependency of `chain/jsonrpc`, and from what I know, chain and runtime are designed to be independent (thus, either `chain/jsonrpc` should be moved somewhere around `near` module to be high-level enough, or a "copy" of a structure should exist somewhere, or we can create a trait to handle that, but it seems to be too generic and creates more problems than it solves)

**Comment by frol** [comment] 2020-02-28 21:29
Reopen to track documentation

**Comment by frol** [comment] 2020-02-28 21:33
@amgando #2109 has relevant examples of `EXPERIMENTAL_genesis_config` API call.

**Comment by amgando** [comment] 2020-04-01 06:11
seems like a duplicate of https://github.com/nearprotocol/nearcore/issues/2025 from a docs perspective.  am i missing something?  closing for now.

nearprotocol/docs#253
https://docs.nearprotocol.com/docs/api/rpc-experimental

**Closed by amgando** 2020-04-01 06:11 UTC
Labels: P2, RPC, misterwhite
