### ISSUE TITLE
Investigate potentially flakiness during handshake

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#3359] opened 2020-09-21 19:00 UTC
As part of https://github.com/nearprotocol/nearcore/issues/3351, I tested syncing with archival nodes from #3302 and noticed that sometimes two nodes running the same commit cannot finish handshake due to handshake timeout. This issue tracks the investigation of the new handshake.

**Comment by mfornet** [comment] 2020-09-23 00:09
@bowenwang1996 I tested locally several times with `tests/sanity/block_sync_archival.py` and handshake never failed. I'll test on different machines next. Is it possible that in the setup you see this nodes had large state, and they consumed large time initializing, affecting first few Handshake attempts?

**Comment by bowenwang1996** [comment] 2020-09-23 03:42
@mfornet did it reproduce with `start_from_genesis.py`?

**Comment by mfornet** [comment] 2020-09-23 04:13
@bowenwang1996 I'm not sure this is the same issue as the one fixed in #3360. The problem fixed there wasn't handshake timeouts, but nodes incorrectly removing some of its peers from the active peer set, leading to constant unsuccessful handshake retry. `start_from_genesis.py` was fixed in #3360, but I'm still unable to reproduce this issue (handshake timeout).

**Comment by bowenwang1996** [comment] 2020-09-23 16:05
> leading to constant unsuccessful handshake retry

Doesn't this cause handshake timeout eventually or did I miss something?

**Comment by mfornet** [comment] 2020-09-24 16:09
> Doesn't this cause handshake timeout eventually or did I miss something?

Not necessarily, and actually while I was debugging that was not the case. When one peer drops the connection, the other peer will note the stream have been closed, and will call to stop the PeerActor, in this case, handshake timeout won't be triggered. This was the actual situation, since one peer was closing connection as soon as it noticed that the inbound peer was already an active connection.

**Comment by bowenwang1996** [comment] 2020-09-25 00:48
I see. Maybe try connecting a node to testnet and see if that helps reproducing the issue. Also I believe #3362 may be related.

**Comment by mfornet** [comment] 2020-09-29 15:06
Fixed in #3397

**Closed by mfornet** 2020-09-29 15:06 UTC
Labels: chain, network
