### ISSUE TITLE
Segfault when running test_three_nodes_sync

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#702] opened 2019-03-11 18:46 UTC
When running `test_three_nodes_sync` in `node/alphanet`, sometimes the test succeeds, but exist with `signal: 11, SIGSEGV: invalid memory reference`.

**Comment by ilblackdragon** [comment] 2019-03-26 21:07
Duplicate of #718

**Closed by ilblackdragon** 2019-03-26 21:07 UTC
Labels: bug, testnet
