### ISSUE TITLE
receipts currently produce TransactionResult

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#519] opened 2019-02-05 01:02 UTC
if we don't want to differentiate between transaction results and receipt results via structs, we should at least rename `TransactionResult` so that it's more explicit

cc: @bowenwang1996

**Comment by bowenwang1996** [comment] 2019-02-05 01:22
Sure. What's a good name for this?

**Comment by bowenwang1996** [comment] 2019-02-05 02:30
I don't know, but it seems that's what we used to do

**Comment by azban** [comment] 2019-02-05 02:33
ok.. i'm playing around with the idea of ripping out some of the transaction address + results into a separate client so i'll see what happens and if we need to keep this in here at all.

**Comment by ilblackdragon** [comment] 2019-02-05 02:58
We do need this structure (status + logs + produced receipts) - because this thing is merkalized and should be queriable.
Name wise - I'm ambiguous. Can be `TransitionResult` for example (e.g. state transition)

**Comment by ilblackdragon** [comment] 2019-03-28 02:23
We didn't decide on renaming at the moment. Closing this as duplicate of #105 for different name for Transaction + Receipt.

**Closed by ilblackdragon** 2019-03-28 02:23 UTC
Labels: invalid
