### ISSUE TITLE
Nightly failure: sanity/state_sync_routed.py manytx 100 times out

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#2547] opened 2020-04-28 17:15 UTC
Times out consistently. Example runs:

http://nightly.neartest.com/run/f625606891dec008a572ca61ec37da500c2a95cd_200428_135923
http://nightly.neartest.com/run/2cef4105736ab969470df2751e78fd3f0fc0a81d_200428_102644

**Comment by SkidanovAlex** [comment] 2020-04-29 00:44
Assigning to Marcelo.

Locally sometimes the test passes, sometimes fails triggering the assert

`assert tracker4.count("Consolidated connection with FullPeerInfo") == 2`

and sometimes gets stuck at the end waiting for `test4` to get their balances updated.
In the logs of `test4` I see this repeatedly:

`Some("test4") Drop signed message to PeerId(ed25519:He7QeRuwizNEhBioYG3u4DZ8jWXyETiyNzFD3MkTjDMf) Reason Disconnected.   ....    body:  StateRequestHeader(0, `88UMTs8pwhjbNX1BvvvUG5VwJxdaMKAW1EsdY9zZ2hYW`) }`

The peer_id corresponds to `test0`, who based on my understanding of the test is banning `test4`. Probably `test4` should not be trying to send messages to a peer that is disconnected?

**Comment by bowenwang1996** [comment] 2020-04-29 18:09
So it seems to me that the reason that the test fails is because we do not route `PartialEncodedChunkRequest` properly, or maybe it is intended and this test is just not well written. What happens is that `test4` tries to request chunks from `test0`, but `test0` is on the blacklist of `test4`, so while `test4` knows the existence of `test0`, it cannot send messages to `test0` and we don't route the request in this case because `test0` is in the routing table of `test4`. I am not sure what is the intended behavior in this case. @SkidanovAlex @mfornet

**Comment by bowenwang1996** [comment] 2020-05-01 16:47
@mfornet it failed again http://nightly.neartest.com/run/e35bc88bfbb364b2cbd0563f5efb3d205643bbb7_200501_154940

**Comment by mfornet** [comment] 2020-05-02 18:56
@bowenwang1996 the problem I see from the logs is that there was not enough time for node4 to enable both of the expected connection. Already fixed on #2602

**Closed** 2020-05-02 19:48 UTC
Labels: chain, nightly
