### ISSUE TITLE
Node account_id can be invalid or non-existant

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#1654] opened 2019-11-05 22:21 UTC
E.g. `{"account_id":"StakingHub","is_slashed":false},`

**Comment by fckt** [comment] 2019-11-11 15:15
Just tested, can't reproduce.. 

```
➜  near near --networkId test-chain-NeaME --nodeUrl http://localhost:3030 create_account Test --masterAccount test.near --keyPath ~/.near/validator_key.json

Loaded master account test.near key from /Users/fro/.near/validator_key.json with public key = ed25519:HjCXzWKkge9DnvEKvGU7yJc6hvSD33wNfw7tadgpSqu1
Error:  TypedError: Invalid receiver account ID "Test" according to requirements
    at JsonRpcProvider.sendJsonRpc (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/providers/json-rpc-provider.js:60:23)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Account.signAndSendTransaction (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/account.js:75:22)
    at async LocalAccountCreator.createAccount (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/account_creator.js:16:9)
    at async Near.createAccount (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/near.js:41:9)
    at async exports.createAccount (/usr/local/lib/node_modules/near-shell/index.js:56:5)
    at async Object.handler (/usr/local/lib/node_modules/near-shell/utils/exit-on-error.js:4:9) {
  type: 'InvalidTxError::InvalidReceiver'
}

**Comment by evgenykuzyakov** [comment] 2019-11-15 17:59
This is a validator Name for node. Not for staking. So if this name is present in genesis, then we don't test it.

**Comment by evgenykuzyakov** [comment] 2019-11-19 19:17
@bowenwang1996 Is it fixed?

**Comment by ilblackdragon** [comment] 2020-03-20 13:50
I'll close it, because it's just an issue of populating genesis. We should just be careful with genesis at this point.

**Closed by ilblackdragon** 2020-03-20 13:50 UTC
Labels: bug, chain
