### ISSUE TITLE
Retrieve all events based on the block hash

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2047] opened 2020-01-30 21:43 UTC
As requested by one of users, they want to know all events that happened across all shards based on the block hash

**Comment by amgando** [comment] 2020-04-01 06:14
not sure why this in the Docs pipeline.  I think i'm missing something here.

**Comment by frol** [comment] 2020-04-02 04:44
I think it is a duplicate of #2128, which is resolved.

**Closed by frol** 2020-04-02 04:44 UTC
Labels: docs
