### ISSUE TITLE
calculate reward cause overflow

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#1561] opened 2019-10-25 21:24 UTC
In today's workshop, after running to block 299,
```
thread 'main' panicked at 'attempt to multiply with overflow', chain/epoch_manager/src/reward_calculator.rs:28:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  14: core::panicking::panic
             at src/libcore/panicking.rs:49
  15: near_epoch_manager::reward_calculator::RewardCalculator::calculate_reward
             at chain/epoch_manager/src/reward_calculator.rs:28
  16: near_epoch_manager::EpochManager::finalize_epoch
             at chain/epoch_manager/src/lib.rs:258
  17: near_epoch_manager::EpochManager::record_block_info
             at chain/epoch_manager/src/lib.rs:329
  18: <near::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::add_validator_proposals
             at near/src/runtime.rs:517
  19: near_chain::chain::ChainUpdate::process_block
             at chain/chain/src/chain.rs:1939
  20: near_chain::chain::Chain::process_block_single
             at ./chain/chain/src/chain.rs:619
  21: near_chain::chain::Chain::process_block
             at ./chain/chain/src/chain.rs:371
  22: near_client::client::Client::process_block
             at chain/client/src/client.rs:442
  23: near_client::client_actor::ClientActor::process_block
             at chain/client/src/client_actor.rs:670
  24: near_client::client_actor::ClientActor::receive_block
             at chain/client/src/client_actor.rs:687
  25: <near_client::client_actor::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
             at chain/client/src/client_actor.rs:204
  26: <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.8.3/src/address/envelope.rs:112
  27: <actix::address::envelope::Envelope<A> as actix::address::envelope::EnvelopeProxy>::handle
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.8.3/src/address/envelope.rs:71
  28: actix::mailbox::Mailbox<A>::poll
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.8.3/src/mailbox.rs:94
  29: <actix::contextimpl::ContextFut<A,C> as futures::future::Future>::poll
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.8.3/src/contextimpl.rs:364
  30: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
  31: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
  32: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
  33: futures::task_impl::Spawn<T>::enter::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
  34: futures::task_impl::std::set
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83
  35: futures::task_impl::Spawn<T>::enter
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
  36: futures::task_impl::Spawn<T>::poll_fn_notify
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291
  37: futures::task_impl::Spawn<T>::poll_future_notify
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
  38: tokio_current_thread::scheduler::Scheduled<U>::tick
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/scheduler.rs:351
  39: tokio_current_thread::scheduler::Scheduler<U>::tick::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/scheduler.rs:330
  40: tokio_current_thread::Borrow<U>::enter::{{closure}}::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:788
  41: tokio_current_thread::CurrentRunner::set_spawn
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:825
  42: tokio_current_thread::Borrow<U>::enter::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:788
  43: std::thread::local::LocalKey<T>::try_with
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/thread/local.rs:262
  44: std::thread::local::LocalKey<T>::with
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/thread/local.rs:239
  45: tokio_current_thread::Borrow<U>::enter
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:786
  46: tokio_current_thread::scheduler::Scheduler<U>::tick
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/scheduler.rs:330
  47: tokio_current_thread::Entered<P>::tick
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:612
  48: tokio_current_thread::Entered<P>::block_on
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:502
  49: actix_rt::runtime::Runtime::block_on::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:128
  50: actix_rt::runtime::Runtime::enter::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:168
  51: tokio_executor::global::with_default::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:209
  52: std::thread::local::LocalKey<T>::try_with
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/thread/local.rs:262
  53: std::thread::local::LocalKey<T>::with
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/thread/local.rs:239
  54: tokio_executor::global::with_default
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:178
  55: actix_rt::runtime::Runtime::enter::{{closure}}::{{closure}}::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:166
  56: tokio_timer::timer::handle::with_default::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:101
  57: std::thread::local::LocalKey<T>::try_with
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/thread/local.rs:262
  58: std::thread::local::LocalKey<T>::with
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/thread/local.rs:239
  59: tokio_timer::timer::handle::with_default
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:84
  60: actix_rt::runtime::Runtime::enter::{{closure}}::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:159
  61: tokio_timer::clock::clock::with_default::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:137
  62: std::thread::local::LocalKey<T>::try_with
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/thread/local.rs:262
  63: std::thread::local::LocalKey<T>::with
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/thread/local.rs:239
  64: tokio_timer::clock::clock::with_default
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:117
  65: actix_rt::runtime::Runtime::enter::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:158
  66: tokio_reactor::with_default::{{closure}}
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:237
  67: std::thread::local::LocalKey<T>::try_with
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/thread/local.rs:262
  68: std::thread::local::LocalKey<T>::with
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/thread/local.rs:239
  69: tokio_reactor::with_default
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:217
  70: actix_rt::runtime::Runtime::enter
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:157
  71: actix_rt::runtime::Runtime::block_on
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:126
  72: actix_rt::builder::SystemRunner::run
             at /home/bo_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/builder.rs:209
  73: near::main
             at near/src/main.rs:160
  74: std::rt::lang_start::{{closure}}
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/rt.rs:64
  75: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  76: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  77: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  78: std::panicking::try
             at src/libstd/panicking.rs:271
  79: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  80: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  81: std::rt::lang_start
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/rt.rs:64
  82: main
  83: __libc_start_main
  84: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in Arbiter thread, shutting down system.
```

**Comment by bowenwang1996** [comment] 2019-10-25 21:48
@nearmax attacked us unfortunately. We'll add check in the genesis tool

**Comment by nearmax** [comment] 2019-10-28 19:22
> @nearmax attacked us unfortunately. We'll add check in the genesis tool

We should fix the runtime, instead of the genesis. Anyone can create a genesis.config manually without the tool and perform the same attack. This is the real issue that should be fixed: https://github.com/nearprotocol/nearcore/issues/1461

**Comment by nearmax** [comment] 2019-11-19 02:47
Duplicate of: #1461

**Closed by nearmax** 2019-11-19 02:47 UTC
Labels: Priority 0, bug
