### ISSUE TITLE
rainbow-bridge test timeout

### ISSUE THREAD

**Issue by frol** [nearprotocol/nearcore#3023] opened 2020-07-22 14:05 UTC
**Describe the bug**

rainbow-bridge tests suite can stuck and break CI: https://buildkite.com/nearprotocol/nearcore/builds/2643#c4bfc018-aaab-46f2-9084-45578d989c65/69-2528 (the PR itself #2997 only touches README file, so it is definitely not related to the code changes)

**To Reproduce**

Unknown. It seems to be flaky.

**Expected behavior**

The tests should pass deterministically.

**Version (please complete the following information):**
- nearcore commit/branch: master

/cc @ailisp

**Comment by bowenwang1996** [comment] 2020-07-22 14:58
duplicate of https://github.com/near/rainbow-bridge/issues/175

**Closed by bowenwang1996** 2020-07-22 14:58 UTC
Labels: bug, testing

**Comment by ailisp** [comment] 2020-07-22 16:25
I made it timeout in 15min, which is enough if it doesn't stuck in future, and less time than param-estimator to make this not bottleneck of ci
