### ISSUE TITLE
Nightly tool to show # of failures

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1799] opened 2019-12-01 20:22 UTC
Currently reporting at http://nightly.nearprotocol.com:8888/ doesn't show any aggregate statistics.
Can add (#failed / #total) and may be duration.

**Comment by ailisp** [comment] 2019-12-02 19:50
Would suggest another enhancement: 
![image](https://user-images.githubusercontent.com/13259400/69990025-c0116880-14f9-11ea-86de-5fb7eb71fe8e.png)
Currently all test names are text. Would be nice to make it clickable, and link to a page show all run of this test.

**Comment by bowenwang1996** [comment] 2020-03-31 01:38
duplicate of #2156

**Closed by bowenwang1996** 2020-03-31 01:38 UTC
Labels: testing
