### ISSUE TITLE
nearcore doesn't always return structured errors

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#2572] opened 2020-04-29 05:32 UTC
**Describe the bug**

When submitting transaction nearcore at least sometimes returns structured errors (usually unfortunately just Timeout). When making a contract method view call – non-structured errors are returned. This may apply to other calls as well – investigation is needed on which RPC calls are affected. 

**To Reproduce**
Make a view call on any contract that results in error.

**Expected behavior**
Structured error is returned.

**Comment by vgrichina** [comment] 2020-04-29 05:34
```
[I] ➜ http post https://rpc.betanet.nearprotocol.com jsonrpc=2.0 method=tx params:='["CqiBnYCRgkGV2odJPXJTBkoZHXjDNQFJKw7oRYWU1j6g", "betanet"]' id=dontcare
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 162
Content-Type: application/json
Date: Mon, 27 Apr 2020 23:14:13 GMT
Server: nginx/1.14.0 (Ubuntu)

{
    "error": {
        "code": -32000,
        "data": "Transaction CqiBnYCRgkGV2odJPXJTBkoZHXjDNQFJKw7oRYWU1j6g doesn't exist",
        "message": "Server error"
    },
    "id": "dontcare",
    "jsonrpc": "2.0"
}
```

**Comment by bowenwang1996** [comment] 2020-04-29 16:20
duplicate of #2536

**Closed by bowenwang1996** 2020-04-29 16:20 UTC
