### ISSUE TITLE
Node unable to start. Opening store database at "/srv/near/data" /usr/local/bin/run.sh  Illegal instruction  

### ISSUE THREAD

**Issue by ethers** [nearprotocol/nearcore#1798] opened 2019-12-01 16:19 UTC
Did all the preceding steps and then tried to do this
https://docs.nearprotocol.com/docs/local-setup/running-testnet#running-official-testnet-node-with-docker

The docker logs show the following:

Telemetry: https://explorer.nearprotocol.com/api/nodes
Bootnodes: AJLCcX4Uymeq5ssavjUCyEA8SV6Y365Mh5h4shqMSTDA@34.94.190.204:24567,EY9mX5FYyR1sqrGwkqCbUrmjgAtXs4DeNaf1sjG9MrkY@35.226.146.230:24567,8K7NG5v2yvSq4A1wQuqSNvyY334BVq3ohvdu9wgpgjLG@104.154.188.160:24567,FNCMYTt9Gexq6Nq3Z67gRX7eeZAh27swd1nrwN3smT9Q@35.246.133.183:24567
[2019-12-01T15:51:34Z INFO  near] Did not find "/srv/near/data" path, will be creating new store database
/usr/local/bin/run.sh: line 25:     7 Illegal instruction     (core dumped) near --home=${NEAR_HOME} run --telemetry-url=${TELEMETRY_URL} --boot-nodes=${BOOT_NODES}
Telemetry: https://explorer.nearprotocol.com/api/nodes
Bootnodes: AJLCcX4Uymeq5ssavjUCyEA8SV6Y365Mh5h4shqMSTDA@34.94.190.204:24567,EY9mX5FYyR1sqrGwkqCbUrmjgAtXs4DeNaf1sjG9MrkY@35.226.146.230:24567,8K7NG5v2yvSq4A1wQuqSNvyY334BVq3ohvdu9wgpgjLG@104.154.188.160:24567,FNCMYTt9Gexq6Nq3Z67gRX7eeZAh27swd1nrwN3smT9Q@35.246.133.183:24567
[2019-12-01T15:51:36Z INFO  near] Opening store database at "/srv/near/data"
/usr/local/bin/run.sh: line 25:     7 Illegal instruction     (core dumped) near --home=${NEAR_HOME} run --telemetry-url=${TELEMETRY_URL} --boot-nodes=${BOOT_NODES}
Telemetry: https://explorer.nearprotocol.com/api/nodes
Bootnodes: AJLCcX4Uymeq5ssavjUCyEA8SV6Y365Mh5h4shqMSTDA@34.94.190.204:24567,EY9mX5FYyR1sqrGwkqCbUrmjgAtXs4DeNaf1sjG9MrkY@35.226.146.230:24567,8K7NG5v2yvSq4A1wQuqSNvyY334BVq3ohvdu9wgpgjLG@104.154.188.160:24567,FNCMYTt9Gexq6Nq3Z67gRX7eeZAh27swd1nrwN3smT9Q@35.246.133.183:24567
[2019-12-01T15:51:39Z INFO  near] Opening store database at "/srv/near/data"
/usr/local/bin/run.sh: line 25:     6 Illegal instruction     (core dumped) near --home=${NEAR_HOME} run --telemetry-url=${TELEMETRY_URL} --boot-nodes=${BOOT_NODES}
Telemetry: https://explorer.nearprotocol.com/api/nodes
Bootnodes: AJLCcX4Uymeq5ssavjUCyEA8SV6Y365Mh5h4shqMSTDA@34.94.190.204:24567,EY9mX5FYyR1sqrGwkqCbUrmjgAtXs4DeNaf1sjG9MrkY@35.226.146.230:24567,8K7NG5v2yvSq4A1wQuqSNvyY334BVq3ohvdu9wgpgjLG@104.154.188.160:24567,FNCMYTt9Gexq6Nq3Z67gRX7eeZAh27swd1nrwN3smT9Q@35.246.133.183:24567

**Comment by bowenwang1996** [comment] 2019-12-01 17:41
This is caused by https://github.com/nearprotocol/nearcore/issues/1746

**Comment by ilblackdragon** [comment] 2020-03-20 20:09
Closing for #1746

**Closed by ilblackdragon** 2020-03-20 20:09 UTC
