### ISSUE TITLE
Node crashes due to storage error

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2623] opened 2020-05-08 22:04 UTC
On betanet we observe that nodes occasionally crash on this line https://github.com/nearprotocol/nearcore/blob/b70cb576a045337d21e30869cdf40f1b92fdbebc/neard/src/runtime.rs#L883. After discussion with @mikhailOK we think that this is not the same issue as #2568, especially given that this happens on an archival node. It requires further investigation to understand what happened there.

**Comment by mikhailOK** [comment] 2020-05-13 18:59
The plan is that #2597 will let us debug these failures

**Comment by Kouprin** [comment] 2020-06-03 06:18
https://github.com/nearprotocol/nearcore/pull/2762 is not enough. I've got 
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StorageInconsistentState("Trie node missing")', chain/chain/src/store_validator/validate.rs:216:16```
while executing Store Validator on test `sanity/skip_epoch.py`. More precisely, check `chunks_state_roots_in_trie()` failed in line `let trie = TrieIterator::new(&trie, &state_root).unwrap();`

**Comment by Kouprin** [comment] 2020-06-03 08:04
@bowenwang1996 @mikhailOK this one seems to be related and important to finish: https://github.com/nearprotocol/nearcore/pull/2775. State should be updated when Chunks are removed. Not sure how it works in case of Forks.

I've removed locally everything that erasing Trie data and `sanity/skip_epoch.py` is still failing with Inconsistent State message "Trie node missing" with turned on Store Validator. It happens in both Master and https://github.com/nearprotocol/nearcore/pull/2775 branches.

**Comment by bowenwang1996** [comment] 2020-06-03 15:24
@Kouprin Does this happen in a single shard system as well?

> State should be updated when Chunks are removed

Why?

**Comment by Kouprin** [comment] 2020-06-03 15:37
> Does this happen in a single shard system as well?

I'm not sure. Many python tests not reproduce this scenario. However, in this particular test, all shards become broken. To reproduce it, you need to remove "TODO return" in `cluster.py` to enable Store Validator.

> Why?

Because the data that available should be consistent. Data from Chunks should be available in Trie and vice versa. If we remove Chunks later than clear Trie, then data in Chunks will be available and data in Trie will not.

**Comment by bowenwang1996** [comment] 2020-06-03 15:59
> To reproduce it, you need to remove "TODO return" in cluster.py to enable Store Validator.

In #2775?

**Comment by Kouprin** [comment] 2020-06-03 16:00
> In #2775?

Doesn't matter. You can use Master branch.

**Comment by mikhailOK** [comment] 2020-06-10 08:18
`process_partial_encoded_chunk` stores the chunk in storage, but looks like we do it even if we're not validating the shard. So we end up with a chunk with `prev_state_root` unavailable.

**Comment by Kouprin** [comment] 2020-06-12 07:51
> `process_partial_encoded_chunk` stores the chunk in storage, but looks like we do it even if we're not validating the shard. So we end up with a chunk with `prev_state_root` unavailable.

After merging https://github.com/nearprotocol/nearcore/pull/2828 "Trie Node Missing" validation result can't be reproduced. However, there is another unexpected inconsistency appeared (https://github.com/nearprotocol/nearcore/issues/2843) and should be fixed separately.

Closing this one as resolved.

**Closed by Kouprin** 2020-06-12 07:51 UTC
Labels: bug, chain
