### ISSUE TITLE
Unexpected error message in state sync

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#1718] opened 2019-11-18 19:33 UTC
During normal state sync, I observe the following error message
```
State sync received hash 8BWrf7oECTej5FAvzCWbbdbvpUsyC9hQRf4v5Eo8MpuG that we're not expecting, potential malicious peer
```

To reproduce, run `sync_empty_state` under `near`.

**Comment by Kouprin** [comment] 2019-11-19 07:25
In `ClientActor::sync` there are some lines of code runs `StateSync` while `HeaderSync` in progress. That's weird because client `SyncStatus` cannot be both `HeaderSync` and `StateSync`.

Seems the problem can be fixed by removing calling `client.state_sync.run` while `HeaderSync` is in progress but we need an explanation from @ilblackdragon.

**Comment by Kouprin** [comment] 2019-11-20 02:12
> In `ClientActor::sync` there are some lines of code runs `StateSync` while `HeaderSync` in progress. That's weird because client `SyncStatus` cannot be both `HeaderSync` and `StateSync`.
> 
> Seems the problem can be fixed by not executing `StateSync` while `HeaderSync` is in progress but we need an explanation from @ilblackdragon.

Discussed with @ilblackdragon offline. That's expected behaviour, so it's important to switch to `StateSync` from `HeaderSync`. Now it seems it's enough to update sync state to `StateSync` when we request a shard from State Sync.

**Comment by Kouprin** [comment] 2019-11-20 02:34
Okay, one more try to describe clearly what's happened.

Before the change, in StateSync we could set `need_shard` true and not set `update_sync_status` true. It seems logical because we don't actually change the state. We left the state as it was before (in `HeaderSync`, for example).

However, after sending StateRequest, the shard is unable to receive StateResponse because it's not in StateSync state. The reason of setting `update_sync_status` true everytime when `need_shard` is true is to let the shard know that it started executing something from StateSync and should change `sync_state` to `StateSync` - even if it doesn't actually change the state.

**Closed** 2019-11-23 01:53 UTC
