### ISSUE TITLE
State sync pytests fail on nightly

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2715] opened 2020-05-23 00:14 UTC
Several state sync tests, including `state_sync.py`, `state_sync2.py`, `state_sync_routed.py` and `state_sync_late.py` are failing on nightly http://nightly.neartest.com/run/master_c034673a56cdc93f7f4dd03ad890911b7ee0f820_20200522_185631.

**Comment by Kouprin** [comment] 2020-05-24 10:25
It seems the nodes finished gracefully and don't start again for some reason. @bowenwang1996 Do you think it's related to State Sync?

**Comment by bowenwang1996** [comment] 2020-05-24 17:07
> don't start again for some reason

Do you mean that when we shut down a node and restart it, it doesn't restart?

**Comment by Kouprin** [comment] 2020-05-27 15:43
Duplicate of https://github.com/nearprotocol/nearcore/issues/2722

**Closed by Kouprin** 2020-05-27 15:43 UTC
