### ISSUE TITLE
Change lto to off by default, and only to on in actual release

### ISSUE THREAD

**Issue by pmnoxx** [nearprotocol/nearcore#3403] opened 2020-09-29 05:05 UTC
Linking process takes around 5m on my machine by default for release build.
I can get it down to 17s by changing `Cargo.toml`.
`
lto = off
codegen-units = 256
`
It would be best not to have to apply this patch patch manually. I was thinking about adding a feature, which turns those flags off.
For example
`
cargo build --release --features "fast_build" -p neard
`

**Comment by bowenwang1996** [comment] 2020-09-29 14:37
Duplicate of https://github.com/nearprotocol/near-ops/issues/169. @pmnoxx please discuss the issue there

**Closed by bowenwang1996** 2020-09-29 14:37 UTC
