### ISSUE TITLE
Fix performance of state dump process

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2070] opened 2020-02-03 21:47 UTC
Currently state dump on TestNet can take up to 1 hour for only ~50MB of state:
 * One reason is Json. We should use a binary format.
 * Another reason is usage of TrieIterator. This can be replace it by just iterating over all values in the STATE column and checking if they are Leafs of the Trie.

Note, let's add this directly to `master` as this is required to actually upgrade our live network.

**Comment by nearmax** [comment] 2020-02-05 14:42
Setting priority to P0 since it is a major requirement for the EthDenver.

**Comment by mikhailOK** [comment] 2020-02-12 02:40
Did an investigation and reopening this issue.
Here are the facts:
- We had an 1 hour state dump incident 8 days ago and opened this issue
- A few days after that we ran into space issue on that node. This resulted into deleting the data that reproduced the issue but also upgrading the disk on that instance
- Since then we were unable to reproduce a slow state dump, json or binary format
- We have no evidence that the 1 hour dump issue that hit json dump won't hit the binary dump

Here is my proposal:
- Revert binary state dump change since it's incorrect (because of rent_paid_at issue) and we don't know if it fixes the 1 hour pathological case
- Keep using json dump but still make a change to deal with 100 MB limit issue
- If we hit a slow dump in the future, save the repro and investigate the cause
- If we hit ~1M blocks on testnet and don't see a huge slowdown, close this issue

**Comment by nearmax** [comment] 2020-02-14 22:35
@bowenwang1996 This is a blocker for the hackathon.

**Comment by bowenwang1996** [comment] 2020-02-15 04:27
As we measured, the speed of state dumping is quite fast. We also have a PR that further improves the speed https://github.com/nearprotocol/nearcore/pull/2126

**Closed** 2020-02-27 18:40 UTC
Labels: P0, housekeeping, storage, upgradeability
