### ISSUE TITLE
test_validator_kickout is flaky 

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#2604] opened 2020-05-02 19:47 UTC
**Describe the bug**
Test `test_validator_kickout` fails some times in CI (failed 1 out of 3 runs locally). Check here: https://buildkite.com/nearprotocol/nearcore/builds/1235#e4eeb06d-d327-436d-a626-ad3f60b7a399

**To Reproduce**

Run locally using:
```
cargo test --package neard --test stake_nodes -- test_validator_kickout --exact --nocapture
```

**Expected behavior**
It shouldn't fail.

---

Also had again error about too many open files while trying to run this test locally:

```
May 02 15:27:18.775 ERROR actix_server::signals: Can not initialize stream handler for Hup err: Too many open files (os error 24)
May 02 15:27:18.775 ERROR actix_server::signals: Can not initialize stream handler for Term err: Too many open files (os error 24)
May 02 15:27:18.775 ERROR actix_server::signals: Can not initialize stream handler for Quit err: Too many open files (os error 24)
thread 'test_validator_kickout' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', chain/network/src/peer_manager.rs:985:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
May 02 15:27:18.775 ERROR actix_server::signals: Can not initialize stream handler for Int err: Too many open files (os error 24)
May 02 15:27:18.787 ERROR actix_server::signals: Can not initialize stream handler for Hup err: Too many open files (os error 24)
May 02 15:27:18.788 ERROR actix_server::signals: Can not initialize stream handler for Term err: Too many open files (os error 24)
May 02 15:27:18.788 ERROR actix_server::signals: Can not initialize stream handler for Quit err: Too many open files (os error 24)
thread 'test_validator_kickout' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', chain/network/src/peer_manager.rs:985:36
thread 'test_validator_kickout' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Non-zero exit code: 1" }', neard/tests/stake_nodes.rs:304:9
test test_validator_kickout ... FAILED
```

Fixed the latter issue using `ulimit -n 8192`

**Comment by bowenwang1996** [comment] 2020-05-02 20:53
duplicate of #2555

**Closed by bowenwang1996** 2020-05-02 20:53 UTC
