### ISSUE TITLE
Rpc requests fail under load

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2402] opened 2020-04-06 19:59 UTC
When there are some load of rpc requests (200 per second), they start to fail with
```
 message: 'request to https://rpc.devnet.nearprotocol.com/ failed, reason: read ECONNRESET',
 message: 'request to https://rpc.devnet.nearprotocol.com/ failed, reason: socket hang up',
 message: 'request to https://rpc.devnet.nearprotocol.com/ failed, reason: Client network socket disconnected before secure TLS connection was established',
```
Our rpc server should definitely be able stand up to such a moderate load.

**Comment by frol** [comment] 2020-04-06 21:35
@bowenwang1996 AFAIK, we don't handle SSL on our own, so this should have something to do with the load balancer (Google Cloud?). I want to add a few facts here:

* My benchmarks of RPC on localhost (https://github.com/nearprotocol/nearcore/issues/2195#issuecomment-603579913) shows that our RPC throughput is in pretty good shape (I tested most of the common RPC endpoints for fetching data, though not the `commit_tx_*`), so 200 rps should not be an issue
* I have seen this HTTPS error before on the Explorer backend, but the only guess I have is that is a DDoS prevention on the load balancer, but I have no idea how to configure that

**Comment by bowenwang1996** [comment] 2020-04-06 22:13
@frol I see, but I definitely think that we need to address this problem because we do plan to use some sort of load balancer to handle rpc requests. It would be quite suboptimal if we cannot even handle 200 rps.

**Comment by ailisp** [comment] 2020-04-11 00:01
I deployed 8 distributed loadtesters from 8 nodes, 128 tps each (as i benchmark a single machine can reliably generate about 220 tps). Each loadtester getting some above three errors, plus this error:
```
0|loadtest  | InternalServerError: <html>
0|loadtest  | <head><title>500 Internal Server Error</title></head>
0|loadtest  | <body bgcolor="white">
0|loadtest  | <center><h1>500 Internal Server Error</h1></center>
0|loadtest  | <hr><center>nginx/1.14.0 (Ubuntu)</center>
0|loadtest  | </body>
0|loadtest  | </html>
0|loadtest  |     at Object.fetchJson (/home/bo_nearprotocol_com/near-ops/loadtest/node_modules/nearlib/lib/utils/web.js:46:36)
0|loadtest  |     at runMicrotasks (<anonymous>)
0|loadtest  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|loadtest  |     at async JsonRpcProvider.sendJsonRpc (/home/bo_nearprotocol_com/near-ops/loadtest/node_modules/nearlib/lib/providers/json-rpc-provider.js:52:26)
0|loadtest  |     at async txnStatus (/home/bo_nearprotocol_com/near-ops/loadtest/util.js:115:12)
0|loadtest  |     at async sendMoney (/home/bo_nearprotocol_com/near-ops/loadtest/loadtest.js:27:30)
0|loadtest  |     at async Promise.all (index 46)
0|loadtest  |     at async /home/bo_nearprotocol_com/near-ops/loadtest/loadtest.js:78:13 {
0|loadtest  |   message: '<html>\r\n' +
0|loadtest  |     '<head><title>500 Internal Server Error</title></head>\r\n' +
0|loadtest  |     '<body bgcolor="white">\r\n' +
0|loadtest  |     '<center><h1>500 Internal Server Error</h1></center>\r\n' +
0|loadtest  |     '<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n' +
0|loadtest  |     '</body>\r\n' +
0|loadtest  |     '</html>\r\n'
0|loadtest  | }
```

Note that if i only start one loadtester there's no such error, so there's still some problem with our node

**Comment by frol** [comment] 2020-04-11 00:38
@ailisp Can you load test the nodes directly without Nginx involved?

**Comment by ailisp** [comment] 2020-04-11 04:20
@frol now loadtest directly with devnet-node4 (one of non validator node), there's only these two errors:
```
0|loadtest |   message: 'request to http://34.94.47.85:3030/ failed, reason: socket hang up',
0|loadtest |   type: 'system',
0|loadtest |   errno: 'ECONNRESET',
0|loadtest |   code: 'ECONNRESET'
0|loadtest | }
0|loadtest | TypedError: [-32000] Server error: Timeout
0|loadtest |     at JsonRpcProvider.sendJsonRpc (/home/bo_nearprotocol_com/near-ops/loadtest/node_modules/nearlib/lib/providers/json-rpc-provider.js:69:27)
0|loadtest |     at runMicrotasks (<anonymous>)
0|loadtest |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|loadtest |     at async txnStatus (/home/bo_nearprotocol_com/near-ops/loadtest/util.js:115:12)
0|loadtest |     at async sendMoney (/home/bo_nearprotocol_com/near-ops/loadtest/loadtest.js:34:30)
0|loadtest |     at async Promise.all (index 80)
0|loadtest |     at async /home/bo_nearprotocol_com/near-ops/loadtest/loadtest.js:94:13 {
0|loadtest |   type: 'UntypedError'
0|loadtest | }
```

**Comment by ilblackdragon** [comment] 2020-04-22 10:17
Moving to Phase 1 as it is not blocking Phase 0 launch.

**Comment by nearmax** [comment] 2020-05-17 02:58
@frol How much time do you think this issue will actually take? Is estimate of 5 days correct?

**Comment by frol** [comment] 2020-05-17 16:32
I don't think there is an actionable item here, at least from the RPC server point of view.

The originally reported errors originate from load balancer limits we decided on for testnet preventing block production issues before. Since the new style of deployment of having RPC-proxy nodes in front of block production nodes, we can disable/relax those limits.

The last errors originate from TIMEOUTs, which are by design.

Well, the actionable item can be to configure load balancers and benchmark again, which is why it is assigned to @ailisp.

**Comment by frol** [comment] 2020-05-17 16:34
Estimation of 5 days is there since we don't know the scope, it can be as simple as no-op after we benchmark again (the benchmark by itself takes our resources, but it should be 1 day effort)

**Comment by nearmax** [comment] 2020-06-04 18:10
Closing in favor of https://app.zenhub.com/workspaces/chainmiddleware-5cea2bcf78297c385cf0ec81/issues/nearprotocol/nearcore/2422

**Closed by nearmax** 2020-06-04 18:10 UTC
